// @vitest-environment jsdom
import * as THREE from 'three';
import { beforeAll, describe, expect, it } from 'vitest';

import { createSmokeTestScene } from '@/rendering/smoke/SmokeTestScene';

import { installCanvas2DStub, readCheckerGrid } from '../support/canvas';

/**
 * Integration coverage for the Phase 0 acceptance path:
 * environment + geometry + textures assembled into a renderable scene graph.
 *
 * A real GL context is not available under jsdom, therefore the assertions
 * target the scene graph itself. The actual draw path is verified by the
 * Playwright suite, which runs a real browser against the production build.
 */
describe('smoke test scene assembly', () => {
  beforeAll(() => {
    // Installed once: every test that assembles a scene needs the 2D context.
    installCanvas2DStub();
  });

  it('produces a checker pattern with two alternating colours', () => {
    // A fresh recorder is installed so that the assertions only observe the
    // textures generated by this scene.
    const recorder = installCanvas2DStub();
    const smoke = createSmokeTestScene();

    // The ground texture (8x8 cells) is generated first, so the first 64 fills
    // belong to it; the cube texture added afterwards would otherwise overwrite
    // cell (0, 0).
    const grid = readCheckerGrid({ fills: recorder.fills.slice(0, 64) }, 128, 8);
    const firstRow = grid[0];
    expect(firstRow?.[0]).not.toBe('');
    expect(firstRow?.[0]).not.toBe(firstRow?.[1]);
    expect(firstRow?.[0]).toBe(firstRow?.[2]);
    expect(firstRow?.[1]).toBe(firstRow?.[3]);

    smoke.dispose();
  });

  it('assembles lights, a shadow receiver and a shadow caster', () => {
    const smoke = createSmokeTestScene();

    const hemisphere = smoke.scene.getObjectByName('environment:hemisphere');
    const sun = smoke.scene.getObjectByName('environment:sun');
    const ground = smoke.scene.getObjectByName('smoke-test-ground');
    const cube = smoke.scene.getObjectByName('smoke-test-cube');

    expect(hemisphere).toBeInstanceOf(THREE.HemisphereLight);
    expect(sun).toBeInstanceOf(THREE.DirectionalLight);
    expect((sun as THREE.DirectionalLight).castShadow).toBe(true);
    expect(ground).toBeInstanceOf(THREE.Mesh);
    expect((ground as THREE.Mesh).receiveShadow).toBe(true);
    expect(cube).toBeInstanceOf(THREE.Mesh);
    expect((cube as THREE.Mesh).castShadow).toBe(true);

    smoke.dispose();
  });

  it('keeps the sun shadow frustum wide enough for a chunk neighbourhood', () => {
    const smoke = createSmokeTestScene();
    const sun = smoke.scene.getObjectByName('environment:sun') as THREE.DirectionalLight;

    expect(sun.shadow.camera.right - sun.shadow.camera.left).toBeGreaterThanOrEqual(32);
    expect(sun.shadow.camera.far).toBeGreaterThan(sun.position.length());

    smoke.dispose();
  });

  it('surfaces a camera whose aspect ratio matches the viewport', () => {
    const smoke = createSmokeTestScene();

    expect(smoke.camera.aspect).toBeCloseTo(window.innerWidth / window.innerHeight, 4);
    expect(smoke.camera.fov).toBeGreaterThan(60);

    smoke.dispose();
  });

  it('animates the cube when updated and stops after dispose', () => {
    const smoke = createSmokeTestScene();
    const cube = smoke.scene.getObjectByName('smoke-test-cube') as THREE.Mesh;

    const before = cube.rotation.y;
    smoke.update(0.5);
    expect(cube.rotation.y).toBeGreaterThan(before);

    smoke.dispose();
    expect(smoke.scene.children).toHaveLength(0);
  });

  it('releases geometry and materials on dispose', () => {
    const smoke = createSmokeTestScene();
    const cube = smoke.scene.getObjectByName('smoke-test-cube') as THREE.Mesh;

    // `BufferGeometry.dispose()` does not clear the attribute arrays; it emits a
    // `dispose` event that the renderer listens to when freeing GPU buffers.
    // Observing that event is therefore the correct leak assertion.
    let geometryDisposed = false;
    let materialDisposed = false;
    cube.geometry.addEventListener('dispose', () => {
      geometryDisposed = true;
    });
    (cube.material as THREE.Material).addEventListener('dispose', () => {
      materialDisposed = true;
    });

    smoke.dispose();

    expect(geometryDisposed).toBe(true);
    expect(materialDisposed).toBe(true);
  });
});
